### ISSUE TITLE
ImportError: cannot import name '__author__' from 'pyjson5.pyjson5'

### ISSUE THREAD

**Issue by RonaldinhoL** [Kijewski/pyjson5#25]
version: 1.6.0
platform: windows10
python:3.9.6

cann't be imported

**Comment by Kijewski** [comment]
Thank you for your bug report! I could reproduce it. I'll look into it.

**Comment by Kijewski** [comment]
I pushed version 1.6.0.post1 for Python 3.7 to 3.10 for Windows to pypi: https://pypi.org/project/pyjson5/1.6.0.post1/#files. It should work fine again for these platforms.
