### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by yohummus** [Kijewski/pyjson5#6]
Hi, thank you for this great library, it runs great under Linux!

Are you planning to support Windows? The installation fails due to the use of __int128 and __builtin_expect which CL does not know. From looking at your it looks like __int128 could be replaced with multiple smaller integers and __builtin_expect could be disabled via a macro.

Cheers,
Johannes

**Comment by Kijewski** [comment]
Hi Johannes, thank you for your kind words! :)

Could you please have a look at #7? There is still some error while linking the library. Maybe you have an idea what is wrong, otherwise I'll investigate later.

**Comment by yohummus** [comment]
Hi René,

thank you for looking into this so quickly 🙂 I've commented on the pull request but I'm not sure why the check fails. It looks like a setup issue with their Windows machines. I can compile and run in locally just fine.
________________________________
