### ISSUE TITLE
builds fails on raspberry pi 4 due to usage of __int128

### ISSUE THREAD

**Issue by chatumao** [Kijewski/pyjson5#8]
I'm not an expert on C++, but as far as I can tell the build fails on the pi because the compiler doesn't support the __int128 type. I read that this type should not even be used because of portability problems, so the question is if it will be changed at some point. Is it really necessary to use such a large data type for parsing?

**Comment by Kijewski** [comment]
Hi, sorry for the late reply! Could you please test if #9 fixes the problem for you?
